os: linux
dist: xenial
sudo: require

language: cpp

jdk: openjdk8

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev
      - odb
      - libodb-dev
      - libodb-sqlite-dev
      - libodb-pgsql-dev
      - libssl-dev
      - libgraphviz-dev
      - libmagic-dev
      - libgit2-dev
      - ctags
      - libgtest-dev
      # Thrift
      - byacc
      - flex
  
before_install:
  - cmake --version
  - g++ --version
  - clang --version
  - llvm-config --version
  - javac -version

install:
  # Thrift
  - |
    if [ ! -f "$HOME/thrift_install/bin/thrift" ]; then
      cd $HOME
      wget -O thrift-0.10.0.tar.gz "http://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=thrift/0.10.0/thrift-0.10.0.tar.gz"
      tar -xvf ./thrift-0.10.0.tar.gz
      cd thrift-0.10.0
      ./configure --prefix=$HOME/thrift_install --without-python --without-php --without-ruby --without-nodejs --without-go
      make install
    fi
  # GTest
  - |
    if [ ! -f "$HOME/gtest_install/lib/libgtest.a" ]; then
      cd $HOME
      mkdir gtest
      cp -R /usr/src/gtest/* ./gtest
      cd gtest
      mkdir build && cd build
      cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/gtest_install
      make
      
      mkdir -p $HOME/gtest_install/lib
      cp libgtest.a libgtest_main.a $HOME/gtest_install/lib/
    fi

before_script:
  # Thrift
  - export CMAKE_PREFIX_PATH=$HOME/thrift_install:$CMAKE_PREFIX_PATH
  - export PATH=$HOME/thrift_install/bin:$PATH
  - thrift --version
  # GTest
  - export GTEST_ROOT=$HOME/gtest_install

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build_pgsql && cd build_pgsql
  - cmake .. -DDATABASE=pgsql -DCMAKE_BUILD_TYPE=Debug
  - make

cache:
  directories:
    - $HOME/thrift_install
    - $HOME/gtest_install
